// SimpleExt.idl : IDL source for SimpleExt.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SimpleExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
[
	object,
	uuid(F751F669-CD9D-4507-9934-7B577027A5AF),
	dual,
	helpstring("ISimpleShlExt Interface"),
	pointer_default(unique)
]
interface ISimpleShlExt : IDispatch
{
};
[
	uuid(DBC3656E-D4E1-40A9-8EF6-4A6B9A94B7AF),
	version(1.0),
	helpstring("SimpleExt 1.0 Type Library")
]
library SIMPLEEXTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(EA8AAA46-6980-4D88-AC1A-C0376E5D451A),
		helpstring("SimpleShlExt Class")
	]
	coclass SimpleShlExt
	{
		[default] interface ISimpleShlExt;
	};
};
